server:
  port: 8080

spring:
  application:
    name: event-ingestor-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 3
        batch.size: 16384
        linger.ms: 10
kafka:
  topics:
    ingestor-output: event.raw.ingested

env:
  aes-key: ThisIsASecretKeyForAESEncryption12